export interface Order {
  id: string;
  date: string;
  items: string[];
  total: number;
  status: string;
  trackingNumber: string;
  shippingAddress: string;
}

export const products = [
  { id: '1', name: 'Wireless Noise-Canceling Headphones', price: 299.99 },
  { id: '2', name: 'Smart Fitness Tracker Watch', price: 129.5 },
  { id: '3', name: 'Ultra-Thin Laptop Sleeve 15"', price: 24.99 },
  { id: '4', name: 'Ergonomic Wireless Mouse', price: 45.0 },
  { id: '5', name: 'Mechanical Gaming Keyboard', price: 149.99 },
  { id: '6', name: 'USB-C Fast Charging Hub', price: 39.99 },
  { id: '7', name: 'Portable Power Bank 20000mAh', price: 59.99 },
  { id: '8', name: '4K Ultra HD Action Camera', price: 199.99 },
  { id: '9', name: 'Bluetooth Waterproof Speaker', price: 79.99 },
  { id: '10', name: 'Smart Home Security Camera', price: 119.95 },
  { id: '11', name: 'Adjustable Laptop Stand', price: 34.99 },
  { id: '12', name: 'Dual Monitor Desk Mount', price: 89.99 },
  { id: '13', name: 'Noise-Isolating Earbuds', price: 49.99 },
  { id: '14', name: 'Wireless Charging Pad', price: 29.99 },
  { id: '15', name: 'USB Condenser Microphone', price: 99.0 },
  { id: '16', name: '1080p Web Camera with Ring Light', price: 65.0 },
  { id: '17', name: 'Portable SSD 1TB', price: 139.99 },
  { id: '18', name: 'High-Speed HDMI Cable 6ft', price: 15.99 },
  { id: '19', name: 'Smart LED Bulb 4-Pack', price: 49.99 },
  { id: '20', name: 'Electric Standing Desk', price: 399.0 },
  { id: '21', name: 'Ergonomic Office Chair', price: 249.99 },
  { id: '22', name: 'Blue Light Blocking Glasses', price: 19.99 },
  { id: '23', name: 'Desktop Air Purifier', price: 89.99 },
  { id: '24', name: 'Robot Vacuum Cleaner', price: 299.99 },
  { id: '25', name: 'Smart Thermostat', price: 199.0 },
  { id: '26', name: 'Video Doorbell', price: 149.99 },
  { id: '27', name: 'Wi-Fi 6 Mesh Router System', price: 279.99 },
  { id: '28', name: 'Network Attached Storage 4TB', price: 349.99 },
  { id: '29', name: '27-inch 4K Monitor', price: 399.99 },
  { id: '30', name: 'Ultra-Wide Gaming Monitor', price: 599.0 },
  { id: '31', name: 'Smartphone Gimbal Stabilizer', price: 119.99 },
  { id: '32', name: 'Ring Light with Tripod Stand', price: 45.99 },
  { id: '33', name: 'Green Screen Backdrop', price: 55.0 },
  { id: '34', name: 'Studio Monitor Speakers', price: 199.99 },
  { id: '35', name: 'Audio Interface', price: 149.0 },
  { id: '36', name: 'MIDI Keyboard Controller', price: 129.99 },
  { id: '37', name: 'Digital Drawing Tablet', price: 89.99 },
  { id: '38', name: 'Stylus Pen for Tablets', price: 29.99 },
  { id: '39', name: 'Tablet Floor Stand', price: 49.99 },
  { id: '40', name: 'Car Phone Mount', price: 19.99 },
  { id: '41', name: 'Dash Cam Front and Rear', price: 129.99 },
  { id: '42', name: 'Bluetooth FM Transmitter', price: 24.99 },
  { id: '43', name: 'Car Jump Starter Power Bank', price: 79.99 },
  { id: '44', name: 'Portable Tire Inflator', price: 45.0 },
  { id: '45', name: 'OBD2 Scanner Diagnostic Tool', price: 39.99 },
  { id: '46', name: 'Camping Tent 4-Person', price: 149.99 },
  { id: '47', name: 'Sleeping Bag Cold Weather', price: 59.99 },
  { id: '48', name: 'Inflatable Sleeping Pad', price: 39.99 },
  { id: '49', name: 'Portable Camping Stove', price: 49.99 },
  { id: '50', name: 'LED Camping Lantern', price: 25.0 },
  { id: '51', name: 'Hiking Backpack 50L', price: 89.99 },
  { id: '52', name: 'Trekking Poles Pair', price: 34.99 },
  { id: '53', name: 'Water Filter Straw', price: 19.99 },
  { id: '54', name: 'Insulated Water Bottle 32oz', price: 29.99 },
  { id: '55', name: 'Polarized Sunglasses', price: 45.0 },
  { id: '56', name: 'Yoga Mat with Alignment Lines', price: 35.0 },
  { id: '57', name: 'Resistance Bands Set', price: 22.99 },
  { id: '58', name: 'Adjustable Dumbbells Set', price: 199.99 },
  { id: '59', name: 'Kettlebell 20 lbs', price: 49.99 },
  { id: '60', name: 'Foam Roller for Muscle Massage', price: 24.99 },
  { id: '61', name: 'Massage Gun Deep Tissue', price: 129.99 },
  { id: '62', name: 'Digital Bathroom Scale', price: 29.99 },
  { id: '63', name: 'Electric Toothbrush', price: 69.99 },
  { id: '64', name: 'Water Flosser', price: 49.99 },
  { id: '65', name: 'Hair Dryer with Diffuser', price: 59.99 },
  { id: '66', name: 'Beard Trimmer Kit', price: 39.99 },
  { id: '67', name: 'Electric Shaver', price: 89.99 },
  { id: '68', name: 'Skincare Mini Fridge', price: 49.99 },
  { id: '69', name: 'Makeup Brush Set', price: 24.99 },
  { id: '70', name: 'Lighted Vanity Mirror', price: 39.99 },
  { id: '71', name: 'Coffee Maker Programmable', price: 79.99 },
  { id: '72', name: 'Espresso Machine', price: 299.0 },
  { id: '73', name: 'Electric Kettle with Temperature Control', price: 59.99 },
  { id: '74', name: 'Coffee Grinder Burr', price: 89.99 },
  { id: '75', name: 'Milk Frother', price: 29.99 },
  { id: '76', name: 'Air Fryer 6 Quart', price: 119.99 },
  { id: '77', name: 'Instant Pressure Cooker', price: 99.99 },
  { id: '78', name: 'Blender for Shakes and Smoothies', price: 89.99 },
  { id: '79', name: 'Food Processor 8 Cup', price: 69.99 },
  { id: '80', name: 'Stand Mixer 5 Quart', price: 249.99 },
  { id: '81', name: 'Chef Knife 8 Inch', price: 49.99 },
  { id: '82', name: 'Cutting Board Set', price: 24.99 },
  { id: '83', name: 'Nonstick Cookware Set', price: 149.99 },
  { id: '84', name: 'Cast Iron Skillet 12 Inch', price: 39.99 },
  { id: '85', name: 'Meat Thermometer Digital', price: 19.99 },
  { id: '86', name: 'Dish Rack Stainless Steel', price: 45.0 },
  { id: '87', name: 'Trash Can with Step Pedal', price: 59.99 },
  { id: '88', name: 'Broom and Dustpan Set', price: 29.99 },
  { id: '89', name: 'Microfiber Cleaning Cloths', price: 15.99 },
  { id: '90', name: 'Laundry Hamper with Lid', price: 34.99 },
  { id: '91', name: 'Bed Pillows Set of 2', price: 49.99 },
  { id: '92', name: 'Duvet Cover Set Queen', price: 59.99 },
  { id: '93', name: 'Fleece Throw Blanket', price: 24.99 },
  { id: '94', name: 'Blackout Curtains 2 Panels', price: 39.99 },
  { id: '95', name: 'Table Lamp with USB Port', price: 45.0 },
  { id: '96', name: 'Wall Clock Silent', price: 25.0 },
  { id: '97', name: 'Picture Frames Set of 5', price: 34.99 },
  { id: '98', name: 'Floating Shelves Wall Mounted', price: 29.99 },
  { id: '99', name: 'Artificial Potted Plant', price: 19.99 },
  { id: '100', name: 'Essential Oil Diffuser', price: 27.99 },
];


export const mockOrders: Order[] = Array.from({ length: 100 }, (_, i) => {
  const orderNum = (1000 + i).toString();
  const startIdx = Math.floor(Math.random() * (products.length - 3));
  const itemCount = Math.floor(Math.random() * 3) + 1;
  return {
    id: `ORD-${orderNum}`,
    date: new Date(Date.now() - Math.floor(Math.random() * 10000000000))
      .toISOString()
      .split('T')[0],
    items: products.slice(startIdx, startIdx + itemCount).map((p) => p.name),
    total: parseFloat((Math.random() * 200 + 20).toFixed(2)),
    status: i % 5 === 0 ? 'Delivered' : 'Processing',
    trackingNumber: `TRK${Math.random().toString().substring(2, 10)}`,
    shippingAddress: `${Math.floor(Math.random() * 9000) + 100} Main St, City, Country`,
  };
});
